### ISSUE TITLE
Remove engine mechanism

### ISSUE THREAD

**Issue by icecrime** [docker/docker#12151]
The whole `/engine` mechanism is complicated, provides not obvious value, makes it harder to follow through the code, and ultimately complicates maintenance: let's get rid of it! 

This includes `engine.Env` as well as it is the primary motivation for this removal.  The ultimate goal is that `/engine` is deleted.

- [x] Remove jobs from `attach` #12120
- [x] Remove jobs from `builder` (wip @calavera)
- [x] Remove jobs from `builtins` #12486
- [x] Remove jobs from `commit` #12279
- [x] Remove jobs from `container_inspect` #12406
- [x] Remove jobs from `copy` #12247
- [x] Remove jobs from `daemon.networkdriver.bridge` #12092
- [x] Remove jobs from `diff` #12183
- [X] Remove jobs from `events` #12066
- [x] Remove jobs from `execCreate` #12472
- [x] Remove jobs from `execStart` (wip @wonderflow)
- [x] Remove jobs from `exec_inspect` (#12305)
- [x] Remove jobs from `export` #12313
- [x] Remove jobs from `graph` #12710
- [X] Remove jobs from `history` #12260
- [x] Remove jobs from `image_export` #12703 
- [x] Remove jobs from `image_set` #12600 
- [x] Remove jobs from `image_get` #12601
- [x] Remove jobs from `images` #12184
- [x] Remove jobs from `info` #12266
- [x] Remove jobs from `kill` #12248
- [x] Remove jobs from `load` #12579 
- [x] Remove jobs from `logs` #12304
- [x] Remove jobs from `ps` #12163
- [x] Remove jobs from `pause`/`unpause` #12249
- [x] Remove jobs from `pull`/`import` #12490
- [x] Remove jobs from `push` #12505
- [X] Remove jobs from `registry.Service` #11974
- [x] Remove jobs from `rename` #12227
- [x] Remove jobs from `resize`/`execResize` #12254
- [x] Remove jobs from `restart` #12350
- [x] Remove jobs from `rm` #12197
- [x] Remove jobs from `rmi` #12234
- [x] Remove jobs from `start`/`create` #12253
- [x] Remove jobs from `stats` #12312
- [x] Remove jobs from `stop` #12306
- [x] Remove jobs from `tag` #12358
- [x] Remove jobs from `top` #12259
- [x] Remove jobs from `wait` #12250
- [x] Remove jobs from `stats` #12312 
- [x] Remove jobs from `trust` #12564

Who will get the final PR that removes `/engine` altogether and closes the issue? :-)

**Comment by tiborvass** [comment]
I added two more (graph and builder)

**Comment by calavera** [comment]
I'll take `builder` to get my feet wet

**Comment by calavera** [comment]
but I cannot edit the issue to put my name on it :cry:

**Comment by vieux** [comment]
@calavera I updated :D

**Comment by tiborvass** [comment]
To anyone willing to work on this, I highly suggest to start with methods on Daemon (like attach). They are much easier. `builder` and all-things-init, are the most tricky ones.

**Comment by runcom** [comment]
@tiborvass may I go with one inside `daemon/`? like `changes.go`?

**Comment by LK4D4** [comment]
@runcom Access granted.

**Comment by runcom** [comment]
@LK4D4 alright thanks! removing from `changes.go`

**Comment by HuKeping** [comment]
hi there, 
why we start removing the engine.Job mechanism anyway, is there any topic i can refer to? Thanks.

**Comment by LK4D4** [comment]
@HuKeping Because it is type unsafe and hard to maintain.

**Comment by icecrime** [comment]
@HuKeping Sorry, we don't have much background to provide indeed. But feel free to come discuss on IRC (#docker-dev on Freenode) if you want more info or want to participate!

**Comment by duglin** [comment]
IMO it also added a layer of indirection that was unnecessary.

**Comment by runcom** [comment]
I've removed eng.Job from `rm` #12197

**Comment by runcom** [comment]
I'm removing from image_delete also

**Comment by HuKeping** [comment]
@icecrime Actually I'd like to +1 for this change, it makes things much more clear, just feel a little sudden in the beginning. 
I'd like to take `rename` as a try, see #12227

**Comment by icecrime** [comment]
Amazing, thanks @HuKeping! I'm trying to keep up updating the first post but things are moving fast :-)

**Comment by LK4D4** [comment]
removing engine from copy

**Comment by runcom** [comment]
removing from pause/unpause

**Comment by duglin** [comment]
doing `top`

**Comment by runcom** [comment]
removing from wait

**Comment by runcom** [comment]
removing from resize (yes, I'm enjoying this thing......)

**Comment by calavera** [comment]
I've started with create and start in https://github.com/docker/docker/pull/12253

**Comment by runcom** [comment]
removing from commit (and implicitly from build_config)

**Comment by HuKeping** [comment]
doing `history`

**Comment by HuKeping** [comment]
doing `info`

**Comment by crosbymichael** [comment]
Updated the description of this issue to help let people know this is ALL of `/engine` not just Jobs.

**Comment by jfrazelle** [comment]
hey so can we make sure when we remove things from `api/server/server_unit_test.go` we add an api test in `integration-cli`. sorry to be a party pooper

**Comment by runcom** [comment]
removing from `inspect` and `logs`

**Comment by dalanlan** [comment]
ping @runcom
actually `ps` & `inspect_container` are using the same handler `getImagesJSON`. So i believe it`s already done there.

**Comment by dalanlan** [comment]
@tiborvass 
i would like to take `graph` :)

**Comment by runcom** [comment]
@dalanlan `container_inspect` job uses `daemon.ContainerInspect` to my best knowledge

**Comment by dalanlan** [comment]
@runcom 
aha, terribly sorry... i misunderstood at the very beginning.
Would you mind if i give it a try?

**Comment by runcom** [comment]
sorry @dalanlan I've alreay done it, just waiting `logs` to be merged so I can rebase it upon :(

**Comment by runcom** [comment]
removing from `restart`

**Comment by wonderflow** [comment]
I noticed that we still need to transfer `eng *engine.Engine` as parameter. And the "getDaemon" hack relies on `Engine`.  Will we finally use `daemon * daemon.Daemon` instead of `eng *engine.Engine` ?

**Comment by icecrime** [comment]
In a ideal world we wouldn't need any global, so I guess `getDaemon` is meant to disappear.

**Comment by runcom** [comment]
removing from `version`!

**Comment by runcom** [comment]
removing from `version` in `builtins`

**Comment by wonderflow** [comment]
@runcom It's claimed here #11620.

**Comment by runcom** [comment]
@wonderflow that's different and can be rebased

**Comment by wonderflow** [comment]
Aha, It's ok for me . :) @runcom

**Comment by runcom** [comment]
At least I think lol the claim on that issue is 20 days old alas I

**Comment by wonderflow** [comment]
Are we need to change  `execCreate` and `execStart`? I noticed they are not in the list.

If so, I'll glad to take it.

**Comment by cpuguy83** [comment]
@wonderflow List is fairly ad-hoc.
End goal is to remove all instances of job (and eventually engine).

**Comment by wonderflow** [comment]
@cpuguy83 Then I'll do it. Thanks!

**Comment by runcom** [comment]
cool! Those are the last left in daemon!

**Comment by icecrime** [comment]
Yes the list tries to follow the work (which is not easy considering the pace!).

**Comment by HuKeping** [comment]
the `info` work has not been merged yet, so  there should not be a √  :)

**Comment by runcom** [comment]
May I call dibs on the final, disruptive remove of engine? :D

**Comment by HuKeping** [comment]
```info``` done.

**Comment by LK4D4** [comment]
Doing trust.

**Comment by LK4D4** [comment]
Doing image_export

**Comment by LK4D4** [comment]
Removing `image_set`

**Comment by runcom** [comment]
removing `image_get`

**Comment by LK4D4** [comment]
doing `image_inspect`

**Comment by runcom** [comment]
doing `image_tarlayer`

**Comment by runcom** [comment]
doing `viz`

**Comment by LK4D4** [comment]
@runcom Encountered same problem with `image_inspect` about runconfig.

**Comment by runcom** [comment]
runco**m**fig I'm coming!
