### ISSUE TITLE
Volume extensions: from experimental to stable

### ISSUE THREAD

**Issue by icecrime** [docker/docker#14213]
# Description

Volume plugins have recently been [merged](https://github.com/docker/docker/pull/13161) as an
experimental feature. We must gather real world use cases and user feedbacks to determine if and
how should this feature be "promoted" to stable.

# How to

- [ ] Determine the predominant deployment model (plugins as containers?)
- [ ] Determine if better introspection is necessary for Swarm

Improve UX where applicable:

- [ ] Do we need a new `plugin` (or similar) top-level command?
- [ ] Do we need an API endpoint to register a new plugin endpoint?
- [ ] Do we need an API endpoint to list available plugins?

**Comment by calavera** [comment]
> Determine the predominant deployment model (plugins as containers?)

I don't think this really matters. We did a good job leaving this up to the plugin implementer.

> Determine if better introspection is necessary for Swarm

I'd like to have a few use cases to understand this better, but we kind of agreed at the maintainers summit that it would be good to send more information to the plugins in the requests. Two things that we thought would be useful where the container id and (maybe) the daemon endpoint.

> Do we need a new plugin (or similar) top-level command?

maybe, if we have very very very good use cases that make it necessary

> Do we need an API endpoint to register a new plugin endpoint?

no

> Do we need an API endpoint to list available plugins?

maybe

## Work in progress to keep in mind:

#13951: Better location for socket and spec files
#13913: Volume creation json payloads (if we made this happen we might not need to add a new TLC)
#13711: Better volume outputs in `docker inspect`.
#13524: Secure connections to plugins.

**Comment by yasker** [comment]
As per discussion at contributor summit, I think providing daemon endpoint probably a little over-doing it.

But I'd like to see we can pass some metadata to plugin, e.g. volume size or base image(which would be used as base for volume creation), something similar to label case, to configure the behavior of the plugin.

**Comment by SvenDowideit** [comment]
I suspect that if we don't pass a daemon endpoint, then plugin authors will hard-code `/var/run/docker.sock` (much like we've hard-coded `/usr/share/docker/plugins`)

**Comment by yasker** [comment]
We probably want to sort out what exactly information plugin would like to get from Docker, hopefully we can just pass the necessary info to plugin. Otherwise it would form an recursive dependence(Docker - plugin - Docker again) and may mess things up.

So far "container id" is an obvious choice, any other things come to mind?

**Comment by vaibhavkhanduja** [comment]
+1 @yasker 

When I started implementing plugin not having "size" as parameter was a bummer. This leads to oversubscription of the volumes on the host storage. Apart from size, I would like following and I have my use-cases mentioned here:

a) Container ID
Today the plugin get volume name, consider a scenario where there is external storage providing storage to multiple container hosts. A volumes name of type containerID + volume name should help. Or I would prefer container name.

b) Encryption keys/user credentials
The volume may be encrypted, an access mechanism for public/private key for reading in volumes.

c) Storage type - useful feature but not important
A database container might need block where as others may be good with file. The storage type could be local or remote.

d) Docker deamon connection details
Similar to docker endpoint, especially needed to run garbage collection in plugin. Though there is an api of remove, but we may never know - host crash, container daemon hosting disk for corrupted etc.

**Comment by cpuguy83** [comment]
My plan in #14242 is to allow the user to pass in a set of k/v option values that just get passed directly to the plugin.

**Comment by vaibhavkhanduja** [comment]
@cpuguy83 perfect

**Comment by yasker** [comment]
@vaibhavkhanduja There are two kinds of information in your list:

1. Container ID, docker daemon connection details: these are informations provided by Docker
2. Keys and storage type etc: these are provided by user.

@cpuguy83 's #14242 would solve item 2, but we still need some work on item 1, which provided by Docker as information to plugin.

**Comment by vaibhavkhanduja** [comment]
@yasker I realized @cpuguy83 mentioned it could be any key value pair? @cpuguy83 ?

**Comment by yasker** [comment]
Since those information can be obtained by Docker, I don't think user would expect something like put container name/id in the command line?

**Comment by vaibhavkhanduja** [comment]
@yasker +1

**Comment by vaibhavkhanduja** [comment]
@calavera 
>>Determine the predominant deployment model (plugins as containers?)
The very fact that volume api's require "path" i.e. mount path be returned, containerizing plugin won't be easy. The containers are chroot with new mount namespace.

**Comment by cpuguy83** [comment]
@vaibhavkhanduja A containerized plugin would certainly need privileged access.

**Comment by vaibhavkhanduja** [comment]
@cpuguy83 I did not quite follow this ... privileged access would right to mount etc ... how would it make mount point available in root mount namespace, especially when mount --make-rprivate / is done?

**Comment by cpuguy83** [comment]
@vaibhavkhanduja Exactly, and we can setup namespaces as needed for plugins.

**Comment by vaibhavkhanduja** [comment]
@cpuguy83 hmmm ... this is interesting ... any more details on how this can be done would help? I know there are api's for setting namespaces - setns, my first thought is that would have be done by plugin. Not easy for plugin too, since the volume api's calls are made before target container is actually started (correct me if I am wrong). I am wondering if this can be done by docker daemon?  ... there are ways, but a cleaner mechanism has to be designed ... dockerizing volume plugin is not straight  :)

**Comment by cpuguy83** [comment]
@yasker I don't think it makes sense to have this on create, because users can create without a container.
However we can pass in the container ID the `Mount` call.

**Comment by yasker** [comment]
@cpuguy83 That's exactly what I meant. Docker should provide this information, likely when do "mount". User shouldn't provide it through cmdline.

**Comment by icecrime** [comment]
Closed by #14659.

**Comment by vaibhavkhanduja** [comment]
@icecrime Are issues raised above taken care?

**Comment by icecrime** [comment]
I haven't read through comments yet to see how the issue has diverged and if we should be filing more about this.

**Comment by vaibhavkhanduja** [comment]
I guess there are things which should be resolved ... through this issue or may be another one?

**Comment by icecrime** [comment]
I'm sorry, I still don't understand the need for passing the container ID. A globally unique (or user defined) ID for the volume, yes, the container ID, no. :-(

**Comment by vaibhavkhanduja** [comment]
@icecrime Can we reopen the issue please? Looks like this needs discussion, other than just docker id there is more info needed in the plugin ..

**Comment by icecrime** [comment]
@vaibhavkhanduja The issue as it was initially meant is "Volume extensions: from experimental to stable". This is solved, and the conversation has derived on another topic.

**Comment by vaibhavkhanduja** [comment]
@icecrime I understand .. so was my question .. should be open an new one? 
..
Can we reopen the issue please? Looks like this needs discussion, other than just docker id there is more info needed in the plugin
..
I am working on a volume plugin, I have worked quite a bit on storage aspects of the applications ...
