### ISSUE TITLE
Document, standardize, and improve the open source process

### ISSUE THREAD

**Issue by icecrime** [docker/docker#14662]
# Description

As the number of docker project grows, we want to have more consistency across repositories. This will make it easier for both contributors and maintainers to move across projects.

# How to

- [x] Reviewing process and Pull Requests labels (#14445)
- [x] Issue triage and Issues labels (#14719)
- [x] Branches and tags (#14720)

# Additional ideas

- Extend @GordonTheTurtle functionalities, for example:
   - Allow for scheduled tasks (e.g., "@GordonTheTurtle Close this in 7 days")
   - Make him move pull requests along the review process
- Automate release note generation
- ...
