### ISSUE TITLE
Enable `golint` on the code base

### ISSUE THREAD

**Issue by icecrime** [docker/docker#14756]
# Description

We want to enable [`golint`](https://github.com/golang/lint) on our codebase for several reasons:
- We want to improve code quality
- We need objective filters on quality to help us discriminate bad pull requests

# How to

Following is the list of all `github.com/docker/docker` subpackages. For each we need to:

- Submit a PR cleaning all existing `golint` warnings. One thing to keep in mind is that `golint` will require that every exported symbol has a comment: favor making symbols private where possible _before_ documenting.
- Enable `golint` on this package as part of the Jenkins CI jobs to make sure we don't diverge (something that individual contributors can do, but @jfrazelle who owns the testing infrastructure will help with that).

We also need to make it easy for contributors to easily give `golint` a local run before submitting the PR. We should probably have that script only cover a hardcoded list of packages that we can augment over time.

# Packages:

- [x] api (@WeiZhang555 - #14844)
- [x] api/client (@brahmaroutu - #14784)
- [x] api/server (@brahmaroutu - #14785)
- [x] api/types (@WeiZhang555 - #14897)
- [X] builder (@hqhq - #14790)
- [X] builder/command (@hqhq - #14790)
- [X] builder/parser (@hqhq - #14790)
- [X] builder/parser/dumper (@hqhq - #14790)
- [x] cliconfig (@MHBauer - #14776 & #15175)
- [x] daemon (@MHBauer - #15310)
- [X] daemon/events
- [X] daemon/execdriver (@hqhq - #14848)
- [X] daemon/execdriver/execdrivers (@hqhq - #14848)
- [X] daemon/execdriver/lxc (@hqhq - #14848)
- [X] daemon/execdriver/native (@hqhq - #14848)
- [X] daemon/execdriver/native/template (@hqhq - #14848)
- [x] daemon/execdriver/windows (@hqhq - #14848)
- [ ] daemon/graphdriver
- [x] daemon/graphdriver/aufs
- [X] daemon/graphdriver/btrfs (@brahmaroutu - #14875)
- [x] daemon/graphdriver/devmapper (@brahmaroutu - #14930)
- [x] daemon/graphdriver/graphtest (@brahmaroutu - #14932)
- [x] daemon/graphdriver/overlay (@brahmaroutu - #15014)
- [x] daemon/graphdriver/vfs (@brahmaroutu - #15092)
- [ ] daemon/graphdriver/windows
- [x] daemon/graphdriver/zfs (@brahmaroutu - #15269)
- [X] daemon/logger (@MHBauer - #14843)
- [X] daemon/logger/fluentd (@MHBauer - #14843)
- [X] daemon/logger/gelf (@MHBauer - #14843)
- [X] daemon/logger/journald (@MHBauer - #14843)
- [X] daemon/logger/jsonfilelog (@MHBauer - #14843)
- [x] daemon/logger/syslog (@MHBauer - #14843)
- [X] daemon/network (@WeiZhang555 - #14796)
- [X] docker (@sevki - #14764)
- [X] dockerinit
- [x] graph (@brahmaroutu - #14827)
- [x] graph/tags (@brahmaroutu - #14828)
- [X] image (@brahmaroutu - #14786)
- [X] integration-cli (@bfirsh - #14851)
- [x] links (@runcom - #14773)
- [x] opts (@sevki - #14813 carried in #15882)
- [x] pkg/archive (@coolljt0725 - #15252)
- [X] pkg/broadcastwriter (@coolljt0725 - #15013)
- [X] pkg/chrootarchive
- [ ] pkg/devicemapper
- [X] pkg/directory
- [X] pkg/fileutils
- [X] pkg/graphdb (@coolljt0725 - #15013)
- [X] pkg/homedir
- [X] pkg/httputils (@coolljt0725 - #15013)
- [X] pkg/ioutils (@coolljt0725 - #15013)
- [x] pkg/jsonlog (@coolljt0725 - #15074)
- [x] pkg/jsonmessage (@coolljt0725 - #15074)
- [X] pkg/listenbuffer
- [x] pkg/mflag (@fcantournet - #14824)
- [X] pkg/mflag/example
- [X] pkg/mount (@runcom - #14817)
- [X] pkg/namesgenerator (@dave-tucker - #14805)
- [X] pkg/nat (@dave-tucker - #14804)
- [X] pkg/parsers (@vdemeester - #14759)
- [X] pkg/parsers/filters (@vdemeester - #14759)
- [X] pkg/parsers/kernel (@vdemeester - #14759)
- [X] pkg/parsers/operatingsystem (@vdemeester - #14759)
- [X] pkg/pidfile (@vdemeester - #14759)
- [X] pkg/plugins (@vdemeester - #14759)
- [ ] pkg/plugins/pluginrpc-gen
- [ ] pkg/plugins/pluginrpc-gen/fixtures
- [X] pkg/pools (@vdemeester - #14759)
- [X] pkg/progressreader (@vdemeester - #14759)
- [X] pkg/promise
- [X] pkg/proxy (@vdemeester - #14759)
- [X] pkg/pubsub
- [X] pkg/random
- [X] pkg/reexec (@LK4D4 - #14762)
- [X] pkg/signal (@vdemeester - #14759)
- [X] pkg/sockets (@vdemeester - #14759)
- [x] pkg/stdcopy (@WeiZhang555 - #15125)
- [X] pkg/streamformatter (@vdemeester - #14759)
- [X] pkg/stringid (@vdemeester - #14759)
- [X] pkg/stringutils (@vdemeester - #14759)
- [X] pkg/symlink
- [x] pkg/sysinfo (@HuKeping - #14840)
- [x] pkg/system (@WeiZhang555 - #15125)
- [X] pkg/systemd (@vdemeester - #14759)
- [X] pkg/tailfile (@vdemeester - #14759)
- [X] pkg/tarsum (@vdemeester - #14759)
- [X] pkg/term (@vdemeester - #14759)
- [X] pkg/term/windows (@vdemeester - #16060)
- [X] pkg/timeoutconn (@vdemeester - #14759)
- [X] pkg/timeutils
- [X] pkg/tlsconfig
- [X] pkg/truncindex (@vdemeester - #14759)
- [X] pkg/ulimit (@vdemeester - #14759)
- [X] pkg/units (@vdemeester - #14759)
- [X] pkg/urlutil
- [X] pkg/useragent (@vdemeester - #14759)
- [X] pkg/version
- [X] registry (@aaronlehmann - #14835)
- [X] runconfig (@vdemeester - #14751)
- [x] trust (@sevki - #14813 carried in #15882)
- [X] utils (@HuKeping - #14801)
- [x] volume (@MHBauer - #14818)
- [X] volume/drivers (@MHBauer - #14818)
- [X] volume/local (@MHBauer - #14818)

Final task:
- [ ] Enable `golint` as part of CI on all non-vendored subpackage (I have the patch ready to fire)

**Comment by runcom** [comment]
+10k

**Comment by vdemeester** [comment]
Oh, I have some work on almost all the ``pkg``. But yeah agree with @runcom, it would be cool (and I think it's already on some other docker project isn't it ?)

**Comment by icecrime** [comment]
@vdemeester Yes, it's enabled on many other docker projects.

**Comment by runcom** [comment]
This is gonna solve #13782 as well (and there's a comment about updating the contribution guide with a note about how we document fields/funs etc etc)

**Comment by vdemeester** [comment]
List of package that already are already *linted* : 
- ``pkg/version``
- ``pkg/urlutil``
- ``pkg/tlsconfig``
- ``pkg/timeutils``
- ``pkg/symlink``
- ``pkg/random``
- ``pkg/pubsub``
- ``pkg/promise``
- ``pkg/listenbuffer``
- ``pkg/homedir``
- ``pkg/fileutils``
- ``pkg/directory``
- ``pkg/chrootarchive``

**Comment by LK4D4** [comment]
I'm taking pkg/reexec for today.

**Comment by vdemeester** [comment]
I'm on these in https://github.com/docker/docker/pull/14759 : 
- pkg/useragent
- pkg/units
- pkg/ulimit
- pkg/truncindex
- pkg/timeoutconn
- pkg/term
- pkg/tarsum
- pkg/tailfile
- pkg/systemd
- pkg/stringutils
- pkg/stringid
- pkg/streamformatter
- pkg/sockets
- pkg/signals
- pkg/proxy
- pkg/progressreader
- pkg/pools
- pkg/plugins
- pkg/pidfile
- pkg/parsers
- pkg/parsers/filters
- pkg/parsers/kernel
- pkg/parsers/operatingsystem

:stuck_out_tongue_closed_eyes:

**Comment by icecrime** [comment]
List updated

**Comment by MHBauer** [comment]
taking cliconfig

**Comment by runcom** [comment]
doing links

**Comment by sevki** [comment]
doing opts

**Comment by brahmaroutu** [comment]
taking api/client api/server

**Comment by icecrime** [comment]
Listed updated :+1: Thanks!

**Comment by coolljt0725** [comment]
taking 
`pkg/archive`
`pkg/broadcastwriter`
`pkg/graphdb`
`pkg/httputils`
`pkg/ioutils`
`pkg/jsonlog`
`pkg/jsonmessage`

**Comment by icecrime** [comment]
Thanks all! I just submitted #14780: when this is in we will be able to update the hardcoded list of cleaned up packages as we progress.

**Comment by hqhq** [comment]
doing:
- builder
- builder/command
- builder/parser
- builder/parser/dumper

**Comment by hqhq** [comment]
and 
- daemon/execdriver*

**Comment by sergiobuj** [comment]
@icecrime I am new to the codebase, would `golint integration-cli` be a bad place to start?

**Comment by brahmaroutu** [comment]
taking image, graph, graph/tag

**Comment by jfrazelle** [comment]
> would golint integration-cli be a bad place to start?

That is going to be ALOT of work

**Comment by hqhq** [comment]
@sergiobuj I think `integration-cli` is a good place to start.
I checked there are not much golint warnings in `integration-cli`, and for golint warnings, I think the most difficult part is to add comments, because you need to understand how these methods and structs work and why we need them. For `integration-cli`, you don't need to understand much Docker codebase, just need to know this test framework, so I think new comings can work on that.

**Comment by vdemeester** [comment]
@icecrime ``dockerinit`` and ``daemon/events`` are already linted too (missed them yesterday).

**Comment by dharmit** [comment]
I am learning golang. Using docker since a while. Would this be a good issue to start with to start contributing to docker?

**Comment by WeiZhang555** [comment]
taking  daemon/graphdriver/*
:)

**Comment by WeiZhang555** [comment]
And also want to try api/ and api/types :)

**Comment by HuKeping** [comment]
take `utils/`

**Comment by dave-tucker** [comment]
taking `pkg/nat`

**Comment by dave-tucker** [comment]
and `pkg/namesgenerator`

**Comment by MHBauer** [comment]
Taking volume/* to start the day.

**Comment by icecrime** [comment]
Woah that's impressive :-) I _think_ the list is up to date, thanks all!

**Comment by runcom** [comment]
doing pkg/mount

**Comment by stevvooe** [comment]
:+1: Obviously, I'm definitely in favor of this.

How do you want us to handle `golint` failures that will cause symbol changes? The following are few that can't be reconciled without changing package interfaces:

- Stuttering names (ie. `archive.Archive`)
- Initialisms (use of `ID` instead of `Id`, using `URL` instead of `Url`)

For the distribution project, we've recommended that people only vendor the package, since the API is not considered stable. I am not sure if docker/docker has made this same recommendation.

I'm in favor of applying the recommendations of `golint` across the board, even if we have to break interfaces. They make for a cleaner and more consistent code base.

**Comment by aaronlehmann** [comment]
I'll claim the registry package.

**Comment by sevki** [comment]
I'll take trust 200 alex

**Comment by fcantournet** [comment]
took pkg/mflag

**Comment by MHBauer** [comment]
daemon/logger and subfriends

**Comment by icecrime** [comment]
We merged #14780 so feel free to add packages to [this list](https://github.com/docker/docker/blob/master/hack/make/validate-lint#L8) as part of your PR to include it naturally in future test runs!

**Comment by vdemeester** [comment]
:+1:

**Comment by brahmaroutu** [comment]
taking daemon/graphdriver, daemon/graphdriver/aufs daemon/graphdriver/btrfs

**Comment by hqhq** [comment]
@icecrime Sorry, I said `daemon/execdriver*`, meant:
- daemon/execdriver (@hqhq - #pending)
- daemon/execdriver/execdrivers
- daemon/execdriver/lxc
- daemon/execdriver/native
- daemon/execdriver/native/template
- daemon/execdriver/windows

Seems `daemon/execdriver/native/template` is already taken? I'll take the rest, can you update?

**Comment by HuKeping** [comment]
taking `pkg/sysinfo/`

**Comment by jfrazelle** [comment]
this is awesome everyone, super cool the enthusiasm to help!

**Comment by peggyl** [comment]
> One thing to keep in mind is that golint will require that every exported symbol has a comment: favor making symbols private where possible before documenting.

@icecrime Isn't this potentially "backwards-compatible" in that other code outside of Docker might be using exported symbols and break when they're made private? Not sure if this is a legitimate concern or just an overabundance of caution.

**Comment by vdemeester** [comment]
- Looking at https://godoc.org/github.com/docker/docker we need to add package documentation as well (at least for ``pkg/*`` packages).
- In #14759 I'll add ``pkg/term/winconsole``

**Comment by bfirsh** [comment]
integration-cli: https://github.com/docker/docker/pull/14851

ping @sergiobuj

**Comment by icecrime** [comment]
@peggyl There's not such thing as overabundance of caution :p My take on this is that the Golang dependency model assumes that changes happen on master, and that downstream should vendor and update at their own pace, so I don't think we should bother. Also if those symbols _can_ be made private to Docker itself, then they most likely shouldn't be part of the package interface anyway.

**Comment by icecrime** [comment]
Thank you all! List updated: I'll update the linted list in CI next.

**Comment by vdemeester** [comment]
@icecrime well, in the end not doing ``pkg/term/winconsole``, see https://github.com/docker/docker/pull/14759#issuecomment-123843604. We'll wait a bit on this one :stuck_out_tongue_closed_eyes:.

**Comment by brahmaroutu** [comment]
Finished aufs and btrfs I can take the rest as they look similar issues with lint? 
daemon/graphdriver/devmapper
 daemon/graphdriver/graphtest
 daemon/graphdriver/overlay
 daemon/graphdriver/vfs
 daemon/graphdriver/zfs

**Comment by icecrime** [comment]
@brahmaroutu Please prioritize getting any of your outstanding PR merged, otherwise sure.

**Comment by brahmaroutu** [comment]
@icecrime I am waiting on review atm.

**Comment by WeiZhang555** [comment]
Is there anyone doing `graph/tags`,`pkg/stdcopy` and `pkg/system`, if nobody is handling these, I would like to have a try.
So taking `graph/tags`,`pkg/stdcopy` and `pkg/system`

**Comment by brahmaroutu** [comment]
@WeiZhang555  graph/tag is already picked up by me.

**Comment by WeiZhang555** [comment]
@brahmaroutu OK, then I'll pick `pkg/stdcopy` and `pkg/system`, if someone has declared one of these already, please tell me. :smile:

**Comment by MHBauer** [comment]
@icecrime What's left? Looks like `daemon` and `graph/tags`. I can give those a shot. `daemon` should be very instructive to document, as a new guy. (I can leave it if that is a better idea).

**Comment by WeiZhang555** [comment]
@MHBauer graph/tags is picked up by @brahmaroutu, so it looks like only `daemon` is left.

**Comment by MHBauer** [comment]
#dibs `daemon` then

**Comment by tiborvass** [comment]
I updated the list, feel free to ping me for any questions

**Comment by Pensu** [comment]
Anything left in this list that I can take up?

**Comment by MHBauer** [comment]
@icecrime #15310 daemon complete and merged.

**Comment by vdemeester** [comment]
@icecrime a PR will be coming soon (probably this week end) with what is left to be *linted* and an update on `validate-lint` too :wink:.
