### ISSUE TITLE
User namespaces - Phase 1

### ISSUE THREAD

**Issue by icecrime** [docker/docker#15187]
# Description

User namespaces are a long awaited feature, on which Phil Estes (@estesp) did some amazing work (see #12648). Unfortunately, the integration unexpectedly conflicted with the recent introduction of [`libnetwork`](https://github.com/docker/libnetwork).

We want to fix this for 1.9.0 and be able to merge Phil's work, which means:
- All containers have their own user namespace (effectively preventing the use of `--net=host` or `--net=container:<id>`).
- A daemon-wide setting remaps the root user for all containers.

# How to

We need the following:
- [X] Patch to libcontainer to enable a hook after namespaces creation (https://github.com/opencontainers/runc/pull/160) - *while the hooks in runc/160 are for runC configs specifically, a separate PR (opencontainers/runc#261) brought the same function into libcontainer directly and is merged and already vendored into Docker with the 0.0.4 vendor merge*
- [x] Patch to libnetwork to enable a single entrypoint to be called in that hook (https://github.com/docker/libnetwork/issues/429) - *PR #16282 was merged 9/14*
- [x] Patch to connect the libcontainer pre-start hook to the new libnetwork sandbox "setExternalKey" function - *PR #16305 merged 9/16*
- [x] Re-submitting the user namespace integration PR (@estesp) https://github.com/docker/docker/pull/12648 - *branch currently has UI as experimental; can be moved into master when necessary*

**Comment by mrunalp** [comment]
PR for hooks in runc https://github.com/opencontainers/runc/pull/160

**Comment by estesp** [comment]
Thanks @mrunalp!

**Comment by bradrydzewski** [comment]
@icecrime would you mind providing more detail regarding this item:

> All containers have their own user namespace (effectively preventing the use of --net=host or --net=container:<id>).

If we are using `--net=container:<id>` today I'm wondering what impact this will have. Will it be possible for a group of containers to share a namespace, effectively accomplishing the same thing as `--net=container`?

**Comment by rhatdan** [comment]
Why is --net=host or --net-container:ID blocked?  Doesn't it just treat the PID as the real UID?

Are we developing --user=containerID?

**Comment by mrunalp** [comment]
With some of the work that is being done in runc, --net-container:ID should work with user namespaces.

**Comment by mrunalp** [comment]
Actually, to correct myself, it will work with some limitations unless the usernamespace is also shared with the other container.

**Comment by thaJeztah** [comment]
For inspiration; here's an old PR and discussion on uid-mappings for User namespaces https://github.com/docker/docker/pull/4572

**Comment by estesp** [comment]
#12648 re-opened and code rebased on current master while runC/libcontainer and libnetwork work is completed.

Todo items:
- [ ] figure out why cgroup mount permission flag change required (d5dcb261f5835097ae1cbbfaba72a27bfdb0f858)
- [ ] resolve Ubuntu 3.16 latest kernel update (and 4.1/4.2) kernel break w.r.t. user namespaces: potentially related to http://www.spinics.net/lists/linux-fsdevel/msg86256.html, but maybe not?
- [ ] need opencontainers/runc#105 finished/vendor updated in **docker/docker** to validate that `docker exec` works appropriately with user namespaced original (init) container process.
- [ ] need opencontainers/runc#160 merged/vendor updated in **docker/docker** to get hook capability for use by libnetwork sandbox code update (to resolve user namespace+net namespace conflict)

ping @mrunalp

**Comment by jfrazelle** [comment]
Sweet @estesp let me know when we can start testing this on a punch of
images to see what we break ;)

**Comment by mrunalp** [comment]
@estesp What do you think about supporting the mappings at docker run time instead of as flags to the daemon?
The first simple implementation would incur the cost of chowning the rootfs while options such as vfs uidshift mount are being figured out. docker commit could either be disabled or made to reverse chown upon save. This way we don't make the implementation too tied to the daemon flag which seems very restrictive in supporting the various use cases for this feature.

**Comment by estesp** [comment]
The root filesystem chown is not too difficult, but the problem is immediately as soon as a second container is started using shared layers with a prior container.  You can't chown the layers already in use.  Basically this model would require moving back to a "dumb" non-CoW graphdriver which copies the entire rootfs on every start (+chown). I'm not averse to considering solutions prior to a more elegant vfs-layer uidshift implementation existing in the kernel, but there are some challenges that seem pretty difficult, and I would at least like to see this "incomplete" function at least be usable in 1.9 so we can begin getting feedback on user namespaces in general.  Thoughts?

**Comment by rhvgoyal** [comment]
@estesp 

I am wondering why can't we continue to use devicemapper graph driver. Their chown should only change those blocks which contain metadata affected by chown. Data should still continue to be shared and we should still continue to enjoy benefits of COW.

I think in case of btrfs this will be akin to "cp --reflink" where metadata in container has changed from 
base image but data continues to be shared.

Once a more optimized vfs uid mapping solution gets implemented (if it gets implemented), moving to that solution should not be a problem.

Am I missing something.

**Comment by estesp** [comment]
@rhvgoyal I think I understand your point now--you want to, at container start time, do a chown in the "top"/"upper" layer of the CoW filesystem of all files in the assembled lower layers, which will basically create a layer of only ownership changes, not affecting the underlying data layers.  While this is definitely a possibility, this means the image can now no longer be used for any further sharing (e.g. docker commit, docker push) as it has a layer embedded within it which makes it specific to this instance of the Docker daemon's (or container's) user mapping.  It seems like a big piece of functionality to give up for user namespaces, given the current implementation handles both pull/push gracefully without impacting the image layer data permanently.

I believe it also would require verifying all graphdrivers in Docker could handle this properly and do it without errors or further complications.  We now have zfs, aufs, overlay, devicemapper, and vfs (naive/flat filesystem driver).

**Comment by estesp** [comment]
Updated the top comment with status, but placing here as well for posterity:
 - opencontainers/runc#261 is merged, Docker vendored runc/libcontainer version already updated as of 9/13 with this change included (PR #16244)
 - docker/libnetwork#502 is merged to handle external sandbox key operations
 - @mavenugo has provided a branch of libnetwork with external sandbox key setting via reexec and the native execdriver changes to add this reexec as a PrestartHook in libcontainer
 - @estesp has tested these 2 changes on top of the updated libnetwork and verified that user namespaces and libnetwork can be used to start a container with network enabled (buildable branch here (build with *experimental* enabled to get `--root`): https://github.com/estesp/docker/tree/userns_libnet_integ

**Comment by mavenugo** [comment]
thanks @estesp I will vendor-in libnetwork today. Also, would like to modify my libcontainer pre-hook integration with daemon slightly. Will make the changes in the PR.

**Comment by rhvgoyal** [comment]
@estesp  For commit case, can't we introduce an option for docker-commit which will reverse map root inside the container to uid 0 and save image. That way you should be able to push/pull images as usual.

**Comment by rhvgoyal** [comment]
But I think this will introduce the problem that commit will put all the files which underwent chown() into diff layer which is not what we want.

**Comment by rhatdan** [comment]
This is a case where building container images and running secure container images conflicts.

**Comment by mrunalp** [comment]
The diff could be enhanced to account for the chown'ing and ignore it on commit, right? @rhvgoyal Will such a strategy not work for any particular fs driver?

**Comment by thaJeztah** [comment]
Wouldn't that result in unexpected behavior if files/directories were explicitly chmod-ed by a process in the container? Or would that need *another* CoW layer on top of the "automatically" created CoW layer?

**Comment by mrunalp** [comment]
@thaJeztah I think there will have to be two layers. One layer just for the chown which could be discarded and the rw layer on top.

**Comment by thaJeztah** [comment]
@mrunalp thanks; I was thinking along that way, but wasn't sure we were on the same page there :-)

**Comment by rhvgoyal** [comment]
@mrunalp, I guess introducing this extra chown layer should work. So if image layer is A, and chown layer is B and final container root will be layer C and when docker commit happens, we should take a diff of C on top of B, map back to uid 0 and save it a layer D with A being the parent layer. Right?

**Comment by rhvgoyal** [comment]
In case of devicemapper, we already have this intermediate layer <ID>-init. May be we can use this layer as intermediate chown layer.

**Comment by mrunalp** [comment]
@rhvgoyal Yes, that's what I had in mind.

**Comment by mavenugo** [comment]
@estesp #16282 brings in the libnetwork changes into docker. 
Also, as discussed, I felt we should also maintain the current modularity & not call libnetwork directly from the native driver. Instead, I did some moeifications to my earlier changes to handle the callback at the docker daemon side & cleanly handled LXC & windows platforms. PTAL : https://github.com/mavenugo/docker/commit/dedc511d3a16b18c066321a11a1a55b6ea57eb16
I have NOT included this patch with #16282. Feel free to use this in your PR if you think it is the correct approach.

**Comment by rhatdan** [comment]
@rhvgoyal @mrunalp The layer stuff would not work if another layer wrote any content to the directory.
from
chown
touch /foobar
unchown

**Comment by icecrime** [comment]
FWIW, I think the code in https://github.com/mavenugo/docker/commit/dedc511d3a16b18c066321a11a1a55b6ea57eb16 is elegant. What do you think @LK4D4 @crosbymichael?

**Comment by mavenugo** [comment]
@icecrime 

> UPDATE Actually, do we really need execDriver.SupportsUserNamespace()? Can't we just do the same for every execdriver and just rely on the callback mechanism? 

Yes, we could. Needs LXC & windows driver changes.

> This boolean won't make sense when we move to runC.

Why ? This boolean was added just to differentiate execdriver capabilities. If LXC or windows doesn't support this functionality, we should still keep it disabled so that libnetwork work as today.

**Comment by crosbymichael** [comment]
I don't see why we wouldn't do this as the default for everything.  I don't think we gain that much by having this functionality only work with userns.

**Comment by mavenugo** [comment]
yes. we can do it as the normal case. I was not sure if this PR will implement the pre-start hook for all other drivers. Sure, the `SupportsUserNamespace` can be changed to `SupportsStartHooks` or something.

**Comment by estesp** [comment]
@mavenugo can correct me if I'm wrong, but I think the baseline issue is that libcontainer today is only used by the Linux native execdriver.  Since hooks only exist in libcontainer, there has to be some mechanism to ignore and/or stub out the Windows and LXC codepaths to not try and use hooks.  Definitely doesn't need to be user ns specific as it is more due to the fact that only libcontainer consumers have hooks.

**Comment by mavenugo** [comment]
@estesp that's correct. That is the reason I added this check now.

**Comment by mavenugo** [comment]
@icecrime now that https://github.com/docker/docker/pull/12648 has all its dependant PRs merged, shall we close this issue ? 
@estesp WDYT ?

**Comment by icecrime** [comment]
Closed by #12648.

**Comment by innocentme1** [comment]
Hey, are usernamespaces enabled by default in 1.12?  I am sure they are not but need a double confirmation on that. Can someone please clarify?

**Comment by thaJeztah** [comment]
@innocentme1 no, they're not *enabled* by default, because they are not suitable for all use cases. See the section here: https://docs.docker.com/engine/reference/commandline/dockerd/#/daemon-user-namespace-options to read about enabling them, but also about some limitations

**Comment by innocentme1** [comment]
yup...thank you :)

**Comment by Wajihulhassan** [comment]
What is the status on container-wide user namespaces such that each container root gets different mapping? Right now in daemon-wide setting all the root users from containers get the same mapping.

**Comment by thaJeztah** [comment]
@Wajihulhassan unfortunately that's not known yet; it depends on upstream changes in the kernel (also see http://www.slideshare.net/PhilEstes/how-secure-is-your-container-containercon-berlin-2016 (slide 18))
