### ISSUE TITLE
Proposal: use of checkers on Integration test

### ISSUE THREAD

**Issue by HuKeping** [docker/docker#16756]
Use c.Assert instead of those conditionals like 
```
if err == nil {
...
}
```
I'll take integration-cli/docker_cli_search_test.go  #16758  as a sample. 

ps: feel free to do a PR with multiple files :smile: 

- [x] integration-cli/docker_api_attach_test.go @mountkin #16920
- [x] integration-cli/docker_api_build_test.go @vdemeester #17056
- [x] integration-cli/docker_api_containers_test.go @aditirajagopal #18216
- [x] integration-cli/docker_api_create_test.go @zelahi #17598 
- [x] integration-cli/docker_api_events_test.go @ZJaffee #17073 
- [x] integration-cli/docker_api_exec_resize_test.go @ZJaffee #17065 
- [X] integration-cli/docker_api_exec_test.go @wenchma #18115
- [x] integration-cli/docker_api_images_test.go @aditirajagopal #18080
- [x] integration-cli/docker_api_info_test.go @aditirajagopal #18148
- [x] integration-cli/docker_api_inspect_test.go @aditirajagopal #18198
- [x] integration-cli/docker_api_inspect_unix_test.go @aditirajagopal #18186
- [x] integration-cli/docker_api_logs_test.go @ZJaffee #17080 
- [x] integration-cli/docker_api_network_test.go @ZJaffee  #17081 
- [x] integration-cli/docker_api_resize_test.go @HuKeping #16971
- [x] integration-cli/docker_api_stats_test.go  @HuKeping #16971
- [x] integration-cli/docker_api_test.go @HuKeping #16971
- [X] integration-cli/docker_api_version_test.go @ZJaffee #17078 
- [x] integration-cli/docker_api_volumes_test.go @HuKeping #16971
- [x] integration-cli/docker_cli_attach_test.go @mountkin #16977
- [x] integration-cli/docker_cli_attach_unix_test.go @wenchma  #17425
- [ ] integration-cli/docker_cli_build_test.go **<- Big one : ~6000 lines** @vdemeester 
- [x] integration-cli/docker_cli_build_unix_test.go @HuKeping #17368
- [x] integration-cli/docker_cli_by_digest_test.go @aditirajagopal #17452 
- [x] integration-cli/docker_cli_commit_test.go @aditirajagopal #17385
- [x] integration-cli/docker_cli_config_test.go @liaoqingwei #17256 
- [x] integration-cli/docker_cli_cp_from_container_test.go @zhangjianfnst #17294
- [x] integration-cli/docker_cli_cp_test.go @zhangjianfnst #17294
- [x] integration-cli/docker_cli_cp_to_container_test.go @zhangjianfnst #17294
- [x] integration-cli/docker_cli_cp_utils.go @zhangjianfnst #17294
- [x] integration-cli/docker_cli_create_test.go @zelahi 
- [ ] integration-cli/docker_cli_daemon_test.go @vdemeester #17138
- [x] integration-cli/docker_cli_diff_test.go @echo33 #17166 
- [x] integration-cli/docker_cli_events_test.go @maaquib #17200
- [x] integration-cli/docker_cli_events_unix_test.go @maaquib #17189
- [x] integration-cli/docker_cli_exec_test.go  @echo33 #17257
- [X] integration-cli/docker_cli_exec_unix_test.go @echo33 #17162
- [x] integration-cli/docker_cli_experimental_test.go @maaquib #17287
- [x] integration-cli/docker_cli_export_import_test.go @maaquib #17222
- [x] integration-cli/docker_cli_external_graphdriver_unix_test.go @fgimenez #17343 
- [x] integration-cli/docker_cli_help_test.go @azurezk #17207
- [x] integration-cli/docker_cli_history_test.go @jecarey #17296
- [x] integration-cli/docker_cli_images_test.go @jecarey #17382
- [x] integration-cli/docker_cli_import_test.go @liaoqingwei #17206 
- [x] integration-cli/docker_cli_info_test.go @liaoqingwei #17196
- [x] integration-cli/docker_cli_inspect_experimental_test.go @liaoqingwei #17167
- [x] integration-cli/docker_cli_inspect_test.go @MHBauer  #16784 
- [x] integration-cli/docker_cli_kill_test.go @zelahi  #17427 
- [x] integration-cli/docker_cli_links_test.go @WeiZhang555 #16854
- [x] integration-cli/docker_cli_links_unix_test.go @WeiZhang555  #16854
- [X] integration-cli/docker_cli_login_test.go @cxxly  #16858
- [x] integration-cli/docker_cli_logs_test.go @zhangjianfnst #16969
- [x] integration-cli/docker_cli_nat_test.go @liaoqingwei  #17008 
- [x] integration-cli/docker_cli_netmode_test.go @cxxly  #16903 
- [x] integration-cli/docker_cli_network_unix_test.go @liaoqingwei #17053
- [x] integration-cli/docker_cli_pause_test.go @liaoqingwei  #17105 
- [x] integration-cli/docker_cli_port_test.go @WeiZhang555  #17100 
- [X] integration-cli/docker_cli_proxy_test.go @liaoqingwei #16870 
- [x] integration-cli/docker_cli_ps_test.go @azurezk  #17009
- [x] integration-cli/docker_cli_pull_local_test.go @aditirajagopal #18199
- [x] integration-cli/docker_cli_pull_test.go  @jecarey  #18714 
- [x] integration-cli/docker_cli_pull_trusted_test.go @Gobella #18004
- [x] integration-cli/docker_cli_push_test.go @HuKeping #16971 
- [X] integration-cli/docker_cli_rename_test.go @Crazykev  #16843
- [x] integration-cli/docker_cli_restart_test.go @echo33 #17004
- [x] integration-cli/docker_cli_rm_test.go @sunyuan3 #16897
- [x] integration-cli/docker_cli_rmi_test.go @WeiZhang555 #16901
- [ ] integration-cli/docker_cli_run_test.go @vdemeester 
- [x] integration-cli/docker_cli_run_unix_test.go @vdemeester
- [x] integration-cli/docker_cli_save_load_test.go @Crazykev #16933
- [x] integration-cli/docker_cli_save_load_unix_test.go @xlgao-zju  #16838
- [x] integration-cli/docker_cli_search_test.go @HuKeping #16758 
- [x] integration-cli/docker_cli_start_test.go @WeiZhang555  #16917
- [x] integration-cli/docker_cli_start_volume_driver_unix_test.go @echo33 #17052
- [X] integration-cli/docker_cli_stats_test.go @cxxly #16881 
- [x] integration-cli/docker_cli_tag_test.go @HuKeping #16846
- [x] integration-cli/docker_cli_top_test.go @HuKeping #16846
- [x] integration-cli/docker_cli_v2_only.go @echo33 #17006
- [x] integration-cli/docker_cli_version_test.go @Mageee #16871 
- [X] integration-cli/docker_cli_volume_test.go @vdemeester
- [X] integration-cli/docker_cli_wait_test.go @cxxly #16889
- [X] integration-cli/docker_hub_pull_suite_test.go @cxxly #16877 
- [x] integration-cli/docker_utils.go @mountkin  #16977

**Comment by thaJeztah** [comment]
Looking at the length of this list, I think you can use some help here :+1:

I'll give a shout in the IRC channel to see if there are maintainers/contributors looking for something to work on :)

**Comment by vdemeester** [comment]
Yeah, we'll split this : I think I'll have to complete this quick to enable easier check writes : https://github.com/vdemeester/shakers. 

@HuKeping could you update the title with something like : Update the use of checkers on Integration test or something ?

**Comment by vdemeester** [comment]
PS : I'll send a PR real quick to integrate more checkers so that it is even easier to write `Assert`s :wink:.

**Comment by MHBauer** [comment]
I'll take a run through `integration-cli/docker_cli_inspect_test.go` to start.

**Comment by vdemeester** [comment]
Cool :+1: I'll reserve `docker_cli_run_test.go` to vendor the checker lib then :sweat_smile:.

**Comment by HuKeping** [comment]
Thanks @thaJeztah it's really a lot of work

Thanks for help @MHBauer 

I'd like to make a sample for people who are interested on this issue,  please help me to complete #16758 @vdemeester

**Comment by zelahi** [comment]
Could I possibly help out on this issue as well?  I can take  integration-cli/docker_cli_kill_test.go to start.

**Comment by HuKeping** [comment]
Cool @zelahi

**Comment by sunyuan3** [comment]
I want to reserve docker_cli_rm_test.go.

**Comment by Mageee** [comment]
I want to reserve `docker_cli_version_test.go`.

**Comment by cxxly** [comment]
I will take integration-cli/docker_cli_login_test.go to start.

**Comment by HuKeping** [comment]
I'll try my best to keep up updating the first post . Thanks @sunyuan3 @Mageee @cxxly

**Comment by Crazykev** [comment]
I want to take `integration-cli/docker_cli_rename_test.go` to start.

**Comment by xlgao-zju** [comment]
I'll take `integration-cli/docker_cli_save_load_unix_test.go`.

**Comment by heartlock** [comment]
I'll take `integration-cli/docker_cli_save_load_unix_test.go` to start .

**Comment by heartlock** [comment]
I‘ll take `integration-cli/docker_cli_pull_test.go` to start .

**Comment by WeiZhang555** [comment]
Cool, I'll take `integration-cli/docker_cli_links_test.go` and `integration-cli/docker_cli_links_unit_test.go`

**Comment by HuKeping** [comment]
I'll pick `docker_cli_t*`

**Comment by icecrime** [comment]
Love the initiative :+1: Thanks! :heart:

**Comment by tiborvass** [comment]
Thanks @HuKeping :)

**Comment by jfrazelle** [comment]
great idea @HuKeping

**Comment by cxxly** [comment]
@HuKeping  I will closed pull request #16836 and recreate it in #16858, please update the list
integration-cli/docker_cli_login_test.go @cxxly #16836   to
integration-cli/docker_cli_login_test.go @cxxly #16858  
sorry for my change, thanks

**Comment by zhangjianfnst** [comment]
Can l take the `integration-cli/docker_cli_links_test.go` and `integration-cli/docker_cli_links_unix_test.go`.

**Comment by zhangjianfnst** [comment]
I want to take `integration-cli/docker_cli_logs_test.go`.

**Comment by cxxly** [comment]
@HuKeping @thaJeztah @vdemeester @zelahi, this is notablle 
"Note that if the comment is constant, a better option is to simply use a normal comment right above or next to the line, as it will also get printed with any errors:" 
in https://godoc.org/gopkg.in/check.v1#Commentf 
thanks @MHBauer

**Comment by liaoqingwei** [comment]
Hi，I will take docker_cli_nat_test.go,docker_cli_network_test.go,docker_cli_pause_test.go,docker_cli_proxy_test.go

**Comment by cxxly** [comment]
@liaoqingwei  I have make a pr in docker_cli_proxy_test.go, you can firstly take docker_cli_nat_test.go,docker_cli_network_test.go,docker_cli_pause_test.go,

**Comment by HuKeping** [comment]
@cxxly it's a good practise that check the issue before submitting an PR :)

**Comment by WeiZhang555** [comment]
`integration-cli/docker_cli_links_unix_test.go` file is also involved in  #16854, please help updated. :)

**Comment by WeiZhang555** [comment]
I'll take another shot, taking `integration-cli/docker_cli_rmi_test.go` and `integration-cli/docker_cli_start_test.go`

By the way, `docker service` command has gone away for now #16645, and `integration-cli/docker_cli_service_test.go` no longer exists, so we can remove it from list

**Comment by HuKeping** [comment]
Thanks @WeiZhang555 , removed.

**Comment by liaoqingwei** [comment]
On 2015/10/9 11:19, Xiaoxu Chen wrote:
> @liaoqingwei <https://github.com/liaoqingwei> I have make a pr in docker_cli_proxy_test.go, you can firstly take docker_cli_nat_test.go,docker_cli_network_test.go,docker_cli_pause_test.go,
> 
> —
> Reply to this email directly or view it on GitHub <https://github.com/docker/docker/issues/16756#issuecomment-146745140>.
> 
OK

**Comment by cxxly** [comment]
takeintegration-cli/docker_hub_pull_suite_test.go and integration-cli/docker_cli_stats_test.go to work

**Comment by thaJeztah** [comment]
Thanks everyone that joined in on this, and started contributing. It didn't go unnoticed, and we're really happy with al your efforts :metal: Open Source FTW!

**Comment by heartlock** [comment]
I'll take ~integration-cli/docker_cli_pull_local_test.go~

**Comment by heartlock** [comment]
I'll take `integration-cli/docker_cli_pull_local_test.go`

**Comment by vdemeester** [comment]
Joining the other maintainers on the :metal: and :heart: !! :heart_eyes_cat:

**Comment by cxxly** [comment]
take  integration-cli/docker_cli_wait_test.go

**Comment by vdemeester** [comment]
@HuKeping updated the merged ones and add a few names too :wink: (hopefully I didn't miss some :sweat_smile: ).

**Comment by cxxly** [comment]
take integration-cli/docker_cli_netmode_test.go

**Comment by heartlock** [comment]
can I take `docker_cli_pull_local_test.go` ?

**Comment by HuKeping** [comment]
@heartlock already added you to it.

**Comment by heartlock** [comment]
sorry ,I forgot to refresh my page

**Comment by echo33** [comment]
I want to take docker_cli_restart_test.go and docker_cli_v2_only.go

**Comment by Crazykev** [comment]
I'll take `integration-cli/docker_cli_save_load_test.go`

**Comment by WeiZhang555** [comment]
Seems there still are integrations left, I'll take one more `integration-cli/docker_cli_port_test.go`

**Comment by Gobella** [comment]
I'll take docker_cli_pull_trusted_test.go

**Comment by azurezk** [comment]
I want to take integration-cli/docker_cli_ps_test.go

**Comment by mountkin** [comment]
integration-cli/docker_utils.go is done in #16977

**Comment by echo33** [comment]
I want to take docker_cli_start_volume_driver_unix_test.go

**Comment by ZJaffee** [comment]
There should also be added docker_api_exec_resize_test.go, docker_api_images_test.go, docker_cli_attach_unix_test.go, I'll take these, but there are possibly more that need to be fixed that weren't added to the check list

**Comment by HuKeping** [comment]
Thanks @ZJaffee I added the `docker_api*` to the list but @vdemeester has removed it.

**Comment by kevinkucharczyk** [comment]
Are there any tests to fix left? Why were the `docker_api*` ones removed?

**Comment by vdemeester** [comment]
@HuKeping ohhh we might have edited the file at the same time :sweat_smile: don't remember having see the `docker_api*` and was wondering why they weren't there.. 

Sorry :blush: I'll add them *back* :wink:

**Comment by HuKeping** [comment]
@kevinkucharczyk they are back :)

**Comment by echo33** [comment]
@HuKeping I have closed #16973 and recreate it in #17004, sorry for the change and I hope you'll update the list, thanks
from integration-cli/docker_cli_restart_test.go @echo33 #16973 
to integration-cli/docker_cli_restart_test.go @echo33 #17004

**Comment by HuKeping** [comment]
Here we go @echo33

**Comment by echo33** [comment]
@HuKeping thanks

**Comment by ZJaffee** [comment]
There is also a test called integration-cli/docker_cli_build_test.go and that is the one which is 6000 lines. I can take care of that one as well.

**Comment by thaJeztah** [comment]
That's a huge list @ZJaffee ! :+1:

**Comment by liaoqingwei** [comment]
I can take `docker_cli_info_test.go` and `docker_cli_inspect_experimental_test.go`,please mark the list.

**Comment by aditirajagopal** [comment]
I would like to reserve `integration-cli/docker_cli_by_digest_test.go` & `integration-cli/docker_cli_commit_test.go`

**Comment by echo33** [comment]
I'll take docker_cli_exec_unix_test.go and docker_cli_diff_test.go.

**Comment by zhangjianfnst** [comment]
@HuKeping I want to take  `integration-cli/docker_cli_cp_*` four files.

**Comment by zelahi** [comment]
I would like to take:  integration-cli/docker_cli_create_test.go

**Comment by maaquib** [comment]
I'll take `integration-cli/docker_cli_events_test.go` and `integration-cli/docker_cli_events_unix_test.go`

**Comment by jecarey** [comment]
I would like to take integration-cli/docker_cli_history_test.go and integration-cli/docker_cli_images_test.go

**Comment by liaoqingwei** [comment]
Seems some files still need to be updated, I will take `docker_cli_import_test.go` and `docker_cli_config_test.go`

**Comment by maaquib** [comment]
I will take `docker_cli_experimental_test.go` and `docker_cli_export_import_test.go`

**Comment by azurezk** [comment]
I want to take docker_cli_help_test.go

**Comment by liaoqingwei** [comment]
@HuKeping Please update the list with the PR #17105 for ·docker_cli_pause_test.go· and #17053 for `docker_cli_network_unix_test.go`

**Comment by HuKeping** [comment]
Done! Thanks @liaoqingwei

**Comment by echo33** [comment]
@HuKeping please update the PR #17052 for docker_cli_start_volume_driver_unix_test.go, thanks
and I want to take docker_cli_exec_test.go

**Comment by fgimenez** [comment]
Hi, I'll take docker_cli_external_graphdriver_unix_test.go

**Comment by wenchma** [comment]
I will take integration-cli/docker_test_vars.go

**Comment by HuKeping** [comment]
Anyone wants to take `integration-cli/docker_cli_build_unix_test.go` as a shoot?

I think there are only `integration-cli/docker_cli_build_unix_test.go` and  ` integration-cli/docker_cli_build_test.go` left and the latter is really a big one > 6000 lines

**Comment by vdemeester** [comment]
I'll take the other big one `docker_cli_build_test.go` :wink: .

**Comment by HuKeping** [comment]
Super cool! @vdemeester

**Comment by wenchma** [comment]
@ZJaffee , found your comment to take `docker_cli_attach_unix_test.go`, if you have not made the pull request, I can take this and give a PR, :smile:

**Comment by stevvooe** [comment]
I wish I had seen this earlier. I really am against these kinds of changes as they can introduce bugs in the name of using some package.

What value does changing from type-safe, compile-time checked, idiomatic Go comparisons to using the very unclear, unfamiliar unit testing framework based on another languages idioms provide?

I just don't see how this:

```
c.Assert(out, checker.Contains, expectedErrorMsg, check.Commentf("expected error message in output: %s", out))
```

Is better than this:

```
if !strings.Contains(out, expectedErrorMsg) {
	c.Fatalf("expected error message %q in output: %s", expectedErrorMsg, out)
}
```

The former requires me to understand the `checker` package and allows any arguments to be passed in. The latter ensures that the test won't even compile if the type of `expectedErrorMsg` changes. It also provides a hint as to how one should use the result of a particular operation in _real_ Go code.

If one needs common or more complex checkers, it is very easy to write them as a helper function or part of a separate package. For example, a common check I define is `checkErr`:

```
r, err = op()
checkErr(t, err)
```

Such a check might have common definitions for the package you're testing. Not only are they more accessible, but they can also be type safe. You get the benefit of both flexibility and specialization that one cannot achieve with an external package.

**Comment by runcom** [comment]
as I've already stated here https://github.com/docker/docker/pull/17452#issuecomment-155201279and on IRC one time with @duglin, my only concern is about the time we'll drop this pkg to move to something else maybe (if we'll move from it of course) and there will be the need to rewrite everything again. This is minor wrt what @stevvooe said above of course..

**Comment by duglin** [comment]
for reference, here's the brief irc chat about this: https://botbot.me/freenode/docker-dev/2015-10-20/?msg=52329998&page=2  before we went off the joys of getting old :-)

**Comment by stevvooe** [comment]
@duglin Following from that, I do find that these kind of assertion frameworks are favored by those unfamiliar or uncomfortable with Go. While that is a completely subjective evaluation, such a package _absolutely_ makes these tests _less familiar_ for seasoned Go programmers that don't use the `check` package. If you believe both premises, we are both making this harder to work with for experienced Go users and harder to work with for new users that have to learn the extra framework.

If there are technical merits for this proposal, other than "I don't like to check error codes", I'd love to hear them.

**Comment by HuKeping** [comment]
Sorry missing the discussing on IRC.

@stevvooe At the very beginning I noticed that there are some test using  `c.Assert(...)` to replace the original comparison and found that is more simple to write the test. And I want to keep the style consistent in the whole project, that's why I make this proposal.

**Comment by stevvooe** [comment]
@HuKeping We already have a style in Go for unit tests. Check out the standard library and other Go projects that avoid unit test frameworks. The tests are more readable, more reliable and more maintainable. Adding the use of `c.Assert` everywhere just complicates test writing.

Is there any technical merit to this proposal? How is transcribing unit tests possibly a good use of anyone's time?

**Comment by vdemeester** [comment]
@stevvooe I hear you and agrees almorst 100% with you on **unit tests** : there is *no* benefits of using "type-safe, compile-time checked, idiomatic Go comparisons" and the built-in framework — on unit tests that is.

> Is there any technical merit to this proposal? How is transcribing unit tests possibly a good use of anyone's time?

On the other end, this proposal is for the **integration test**, not *unit test* (it's even written on the title of this issue), and I believe could escape a bit that. It's a bit more "expressing" the behavior and less about *idomatic Go* (in my opinion) — we could even have written them in bash script (using bats for example) like Swarm does. To disgress a little bit, it's like end-to-end testing or behavior testing, it feels more natural to write them in a more *human* language, like cucumber for example.

I also do agree that some of the assert are readable and some are not :sob: — but I just feel like there is a balance to find not *"use everywhere"*, or *"use nowhere"*.

```go
c.Assert(out, checker.Contains, expectedErrorMsg, check.Commentf("expected error message in output: %s", out))
// The above one could be written like :
c.Assert(out, checker.Contains, expectedErrorMsg)
// The output would be the same (or more accuratly, 
// there is duplication in the output for the first as go-check 
// prints out the arguments if the assertion fails)

// Go checks also prints out comments above the assertion if needed
out, _ := dockerCmd(c, "run", "busybox", "echo", "hello")
// It should have been able to start the container and echo "hello"
c.Assert(out, checker.Equals, "hello")

// I also feel like …
c.Assert(err, checker.IsNil) 
// … is not worse than
if err != nil {
   c.Fatal(err)
}
```

My point is, in my opinion, it's fine to digress a bit of the *idiomatic Go* (which I love a whole lot) for things like *integration-tests* if it helps me to write them quicker and with less noise. Agree to disagree with me but I don't think [this](https://github.com/docker/docker/blob/master/integration-cli/docker_cli_info_test.go#L41) look unreadable.

As @duglin pointed out on IRC, I feel there is a balance to find on that, and I'm old-school too, I like when it fits into 80 cols :wink: :sweat_smile:.

> we'll drop this pkg to move to something else maybe (if we'll move from it of course) and there will be the need to rewrite everything again

@runcom you are right, but we are basically a lot tied up with `go-check` on integration test anyway (we are using the Suite), so the *pain* to move away from it wouldn't be too much *less* painful that it is without it.

**Comment by stevvooe** [comment]
@vdemeester I don't disagree with your assertion that these are integration tests. Bats would have been a better choice. But, we are in Go and Go doesn't do DSLs well like ruby (cucumber).

I am not sure that I can do anything to change the direction of this proposal but I hope this feedback can be valuable for your next project.

From here, I am going to babble on about the problems with the `check` package. Sorry for the book.

---
The following is Go code:

```go
if err != nil {
   c.Fatal(err)
}
```

I trust the above. And despite the annoyance, I have written the construction umpteen thousand times. I know how it behaves. I know the edge cases. It is trustworthy. I have no clue what `c` is but I can guess because I've see functions like that and know how they might behave. 

The following is a package call:

```go
c.Assert(err, checker.IsNil) 
```

It begs many questions. What is `c`? What arguments does `c.Assert` take? What is `checker`? A package? What is `checker.IsNil`? How do they test if something is `nil`? Does it differentiate between being a typed `nil`? Or an unset nil interface? What if I change the argument order?

Let's answer these by looking at [godoc](https://godoc.org/gopkg.in/check.v1#C). Interesting. The `testing.T` type has been replaced by `check.C`. It now combines testing, assertion, benchmarking and helper into a single class.

So, now we look into `checker`. O, it is a docker package, that has redefined `IsNil`, redirecting it back to the `check` package. We eventually arrive at [`isNil`](https://github.com/go-check/check/blob/v1/checkers.go#L117). Wait. What is that? It uses reflect to dip down into the type. Let's look at the documentation for [`reflect.Value.IsNil`](https://golang.org/pkg/reflect/#Value.IsNil). There is a curious bit in there, bolded for emphasis:

> IsNil reports whether its argument v is nil. The argument must be a chan, func, interface, map, pointer, or slice value; if it is not, IsNil panics. __Note that IsNil is not always equivalent to a regular comparison with nil in Go.__ For example, if v was created by calling ValueOf with an uninitialized interface variable i, i==nil will be true but v.IsNil will panic as v will be the zero Value.

O, okay, so `c.Assert(value, IsNil)` does not actually provide an equivalent check for `value == nil`. This can hide some atrocious bugs.

These are all issues and we haven't even got to the part where we realize that these tests aren't composable with other tests that _don't_ use the `check` package. We also haven't gone into how silly this all is when we're just looking to make a statement or call a function.

---

My point isn't necessarily that this is bad or wrong. But, please, examine the amount of cognitive load required to analyze a simple statement. In the Go example, we can evaluate it almost instantly. We don't know what `c` is, but we can infer the behavior or look at a package doc. In the `Assert` example, we traversed through three other packages, eventually landing in the `reflect` package, learning that what we thought is a `nil` test is not quite the same. This extra amount of work goes down as you learn the package, but it must be paid by each new developer working on the code base.

In my experience, testing frameworks tend to be the enemy of test maintenance in code bases maintained by a large, diverse team. In the hands of a small team, additions, such as mocking libraries, test helpers, and frameworks, are a wonderful productivity boost. In larger teams, they detract from test maintainability, as it requires the more casual developers to ramp up on the uncommon additions. I have seen this in large code bases in Java, Ruby and Python, especially with the use of mocking frameworks. Even if you learn a given framework, there may also be overhead in learning how to execute it correctly within a projects chosen build system.

---

In reality, I am not altogether curmudgeonly on this issue. I do see the need for common check functions. We can do this by simply using a check function pattern. A check function is any function that matches the following signature:

```go
func(t *testing.T, ...)
```

Such a function takes a `*testing.T` and fails the test if the check fails. Instead of leveraging reflection, we use type safety to let unit tests fail at compile time when something doesn't go correctly:

```
func checkErr(t *testing.T, err error) {
    if err != nil {
        t.Fatalf("unexpected error: %v", err)
    }
}
```

Simple, composable and type-safe, the above has a few problems. The most problematic is that it is hard to find where the error was generated. There is a very simple solution to that. Let's define an interface for `testing.T`:

```go
type Reporter interface {
    Fatalf(format string, args...interface{})

    // ... and maybe other testing.T fields
}

// new function signature for checkErr
func checkErr(r Reporter, err error)
```

And a simple function that captures the line number and puts it into the report:

```go
func Case(t, format string, args... interface{}) Reporter { /* ... capture line number and msg ...*/ }
```

Then, we can have a very consistent API:

```go
f, err := riskyOp()
checkErr(Case(t, "operation shouldn't be risky"), err)
```

Seems a little verbose, right? Well, actually, this method works amazingly when using nested checks that identify the exact failure line. Let's say we are checking an http response:

```go
// test doHTTP() (*http.Request, error)
r := checkResponse(
    Case(t, "an http response that demonstrates my point"),
         200, doHTTP())

func checkResponse(r Reporter, status int, r *http.Request, err error) *http.Request {
    checkErr(r, err)
    
    // this could even be another function!
    if r.StatusCode != status {
        r.Fatalf("unexpected http status: %v != %v", r.StatusCode, status)
    }
}
```

The above not only let's identify the actual test case that caused the failure, but also does so provided both the line number of the test case and possibly where it failed in the checker stack. The functionality provided by `Case` can also stack, meaning that we can have context to the failure all the way through the check chain.

We can get all this and still don't have to depart from the standard unit testing framework while using idiomatic Go. This could all be part of a package but simple check functions are so easy to write that you can just add it, as part of the project. The only component I would recommend distributing is the `Case` function and the `Reporter` definition, but it is easy to get by without it.

**Comment by aditirajagopal** [comment]
Upon further review, looks like @calavera closed a bunch of PRs & a bunch of these haven't been touched in a while. Can I go ahead and call #dibs on the following?:
<code>docker_api_images_test.go</code>
<code>docker_api_containers_test.go</code>
<code>docker_api_exec_test.go</code>
<code>docker_api_info_test.go</code>
<code>docker_api_inspect_test.go</code>
<code>docker_api_inspect_unix_test.go</code>
<code>docker_cli_pull_local_test.go</code>
<code>docker_cli_pull_trusted_test.go</code>

Also ping @HuKeping - I verified that the following can be marked as "done" in your initial checklist:
<code>docker_api_attach_test.go</code>
<code>docker_cli_by_digest_test.go</code>
<code>docker_cli_cp_from_container_test.go</code>
<code>docker_cli_cp_test.go</code>
<code>docker_cli_cp_to_container_test.go</code>
<code>docker_cli_cp_utils.go</code>
<code>docker_cli_events_test.go</code>
<code>docker_cli_help_test.go</code>
<code>docker_cli_images_test.go</code>
<code>docker_cli_links_test.go</code>
<code>docker_cli_links_unix_test.go</code>
<code>docker_cli_ps_test.go</code>
<code>docker_cli_create_test.go</code>
<code>docker_cli_run_unix_test.go</code>

And <code>docker_cli_network_test.go</code> should be removed from the list because it does not exist

Thanks!

**Comment by HuKeping** [comment]
@aditirajagopal oh sure, please. I'm not on my office these days, so sorry for the late.

**Comment by aditirajagopal** [comment]
@vdemeester, do you need help with docker_cli_run_test, docker_cli_build_test and/or docker_cli_daemon_test? If you have higher priority items to work on, I can take care of these :smile: 

ping @HuKeping - all the other tests have been taken care of!

**Comment by aditirajagopal** [comment]
ping @vdemeester @HuKeping - any thoughts?

**Comment by HuKeping** [comment]
hi @aditirajagopal , `docker_cli_pull_test`  is free to go I think, but not sure about the other claimed by @vdemeester

**Comment by jecarey** [comment]
@HuKeping, I talked to @aditirajagopal and she is ok with me working on docker_cli_pull_test, can you please assign it to me?

**Comment by HuKeping** [comment]
Sure @jecarey

**Comment by aditirajagopal** [comment]
ping @HuKeping -- only docker_cli_run_test, docker_cli_build_test and docker_cli_daemon_test are left. The rest have been completed

**Comment by HuKeping** [comment]
Cool! Thanks @aditirajagopal

**Comment by aditirajagopal** [comment]
@HuKeping I think this issue can be closed/marked as resolved. The remainder of the files that need to be changed involve effort that goes beyond scope of this issue.

**Comment by vdemeester** [comment]
@aditirajagopal @HuKeping or at least I would put it in pause for the time being. I intend to split those in several smaller/cleaner files to be easier to review and update :wink:

**Comment by HuKeping** [comment]
Thanks for everyone the great work you've done here! As @aditirajagopal says, this issue can be marked as resolved and we closing it.

Thanks, again for everyone!

**Comment by thaJeztah** [comment]
![woohoooo](https://cloud.githubusercontent.com/assets/1804568/12141740/7f61f78c-b472-11e5-82be-3d1d8661dc16.gif)
