### ISSUE TITLE
[test-integration] improvements

### ISSUE THREAD

**Issue by vdemeester** [docker/docker#31410]
Several improvements can be done on the integration test side of `docker/docker`. This issue is there to list them and track the work on it.

- [ ] Remove `utils_test.go`, latest `runCommandWithOutput` appearance
- [ ] Remove `docker_utils_test.go`
  - [ ] Move cleanup function to `environment` package #30759 @vdemeester
  - [ ] Extract `fakeContext`, `buildImage`, `inspect`, `dockerCmd`, … methods in packages
- [ ] Make all test suite manage their own deamon. This should allow to use always the same method (instead of currently either `dockerCmd` or `s.d.Cmd`) and this would fix #17129
- [ ] Replace `request` deprecated function (`SockRequest`, `SockRequestRaw`) usage to the new ones (`Get`, `Post`, `Put`, `Do`, …). @vdemeester
- [ ] Rename `test-integration-cli` into `test-integration`. We are testing more than `cli`, it should probably be `test-integration/cli` and `test-integration/api`, …
- [ ] Extract suites in their own packages
  - [ ] start with the API suite that is different enough from the other
  - [ ] Create an `ExperimentalTestSuite` and remove the current experimental build (experimental is not a different binary anymore, we just need a suite where the deamon is with `--experimental`). @vdemeester
  - [ ] Update this to insert other potential suites
- [ ] Maintain integration test suite (probably should be an external issue in the future)
  - [ ] Review `docker_cli_build_test.go` and clean what can be cleaned :angel: 
  - [ ] …
- [ ] List and remove integration tests that could be unit test. One example is some cli-only tests. These should be removed once #31217 is taken care of. I'll also list the one I think could be replaced by unit-test in another issue.

/cc @icecrime @thaJeztah @docker/core-engine-maintainers

**Comment by ripcurld0** [comment]
@vdemeester I would love to work on this too.
Do you need some help? Do you have something that I can begin with?

**Comment by vdemeester** [comment]
@ripcurld0 I think #31217 would be a good start 👼

**Comment by sbko** [comment]
@vdemeester Can I try to help you with "Replace request deprecated function (SockRequest, SockRequestRaw) usage to the new ones (Get, Post, Put, Do, …)."?

**Comment by vdemeester** [comment]
@sbko I'm gonna update this issue a bit with content from [Evolution of testing @moby](https://forums.mobyproject.org/t/evolution-of-testing-moby/38) but yeah any help is more than welcome 👼.

**Comment by sbko** [comment]
@vdemeester do I need to open a separate issue for that task or this one is enough?

**Comment by vdemeester** [comment]
@sbko this one is enough 😉

**Comment by sbko** [comment]
Based on "Evolution of testing" I can start replacing **SockRequest**, **SockRequestRaw** with proper functions from **client/**, correct?

**Comment by vdemeester** [comment]
@sbko right — so my basic idea is that those who uses `request` package could be rewritten with `client` package, but it also depends or where we go with #33344 👼

**Comment by sbko** [comment]
@vdemeester can you take a look at this [commit](https://github.com/sbko/moby/commit/8a4ac2f65a28c57d9314cea11a3566382fbbbf06)
am I doing the right thing? thanks!

**Comment by sbko** [comment]
@vdemeester just a heads up that I'm still working on it. there are a lot of changes :)
