### ISSUE TITLE
Supervisor/foreground mode

### ISSUE THREAD

**Issue by crosbymichael** [docker/docker#5305]
This is a small todo list for tasks that can be worked on for decoupling the runtime for containers from the actual daemon.  I'm trying to make this list from what we discussed the other day.  I think each of these tasks can be broken down into small PRs to save us from a mega merge. 

I know there is alot missing from the list but it's a start, if you think of more just update the issue or comment. 

ping @creack @vieux @alexlarsson @shykes 

### TODO:
- [ ] Use fork/exec in dockerinit so that we are PID 1
- [ ] move state out of the container struct
- [ ] allocate IPs on container create and let them last the lifetime of the container (maybe)
- [ ] write code to reap zombies if we are PID 1
- [ ] decouple diff from the graph drivers

**Comment by aidanhs** [comment]
Has this gone anywhere? Is anyone/did anyone work on it?
I assume it's a prerequisite for #6851. Over a year on, is this still an accepted proposed design?
