### ISSUE TITLE
Collected issues with Volumes

### ISSUE THREAD

**Issue by cpuguy83** [docker/docker#6496]
- [ ] #3639 - Volumes don’t work for base images
- [ ] #2259 - Setting permissions on bind mounted volumes
- [ ] #3949 #5229 - Build-only data
- [x] #1992 - `docker cp` doesn’t work with volumes
- [x] #3782 - recursive bind mounting (--rbind instead of —bind)
- [x] #3634 #4356 - volume garbage collection (last comment) # can be handled with named volumes and external volume drivers
- [x] #4023 - Mount remote volumes (client is remote, path is local to client)
- [ ] #2045 - dynamically change volumes
- [x] #6504 - Volume recovery (after corrosponding container removed) # named volumes resolves this
- [x] #6556 - Backup/restore volumes
- [x] #6698 - Volumes need data-containers to be useful - # hanlded by named volumes and external volume drivers
- [ ] #7054 - Expand perm handling of volumes

**Comment by calavera** [comment]
This is very out of date. I rather not maintaining an out of date list, specially since the issues described here are already in other issues.

Closing.

**Comment by cpuguy83** [comment]
Wasn't really out of date, I just touched last week, but ok :)

**Comment by md5** [comment]
Perhaps this would be a good case for a label like `area/volumes`.
