### ISSUE TITLE
Proposal: Make USER change the uid and gid of COPY'd files

### ISSUE THREAD

**Issue by cyphar** [docker/docker#7537]
The current `USER` directive changes the user which every `RUN` directive executes under. However, file copying instructions such as `ADD` and `COPY` are always copied with the owner being `root:root`. This was originally added in 026aebdebbaa05eab25134949ed5d5bda655ba67, in order to fix #2684 and #3950. However, this results in an inconsistency in the `Dockerfile` interface, since `USER` can modify some directives, but not all of them.

I propose that the `COPY` directive should change the owner of any copied file to be the uid of the current user (as set by the `USER` directive and found by parsing `/etc/shadow` in the container -- or failing that, just setting it to nobody [`65534`]) and the gid should be the primary gid of the current user (as found by parsing the `/etc/shadow` file in the container -- or failing that, just setting it to `nobody` [`65534`]).

**NOTE**: After discussing this proposal on the IRC, it was decided that `ADD` should not be modified along the lines of this proposal (since it must be supported and backward compatible until it is deprecated and removed). To this end, I am only proposing that `COPY` should be modified, due to it's relative newness and since there is nowhere near as many backward compatibility concerns as with `ADD`.

---

**EDIT**: I propose a modification to the above proposal, such that:

* If the `b.Config.User` is set to an empty string, then the same method as used in `libcontainer` is applied -- `syscall.Getuid()` and `syscall.Getgid()` are used instead.
* If `b.Config.User` does not exist in `/etc/passwd`, then the builder emits an error.

Does anyone have any objections with the above modification to the proposal?

---

To assist in the tracking of patchsets and pull requests which are required to implement this proposal:

* [x] docker/libcontainer#158: `libcontainer` patchset to expose internal functions for parsing and filtering `/etc/{passwd,group}` files (allowing arbitrary `io.Readers` and thus container `/etc/{passwd,group}` files to be parsed).
* [x] docker/docker#9023: `docker` patch to use the above `libcontainer` patch.
* [ ] docker/docker#9046: actually implement the above proposal (and document it).

---

/ping @shykes and others.

**Comment by masom** [comment]
:+1:

**Comment by cyphar** [comment]
@crosbymichael has closed the implementation PR, because apparently some functionality is "in the works" that would allow for (among other things) this functionality.

**Comment by sarath** [comment]
@cyphar  is there a issue id we can refer to/track progress?

**Comment by cyphar** [comment]
@sarath I am not sure, it was discussed on #docker-maintainers quite recently. If worse comes to worse and you **need** this functionality, you can use my patches (#9046) to patch your own version of Docker. *N.B* This is universally considered as a bad idea, because it will require you to update my patches with upstream changes.

**Comment by thaJeztah** [comment]
@cyphar Oops sorry for that, I should probably have put pinged you there. @unclejack as well because he was assigned to carry it. :smile:
